version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/public:/app/public
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    restart: unless-stopped
