version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    restart: unless-stopped
  
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public/
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
    restart: unless-stopped

volumes:
  redis:
    driver: local